/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings/password` | `/settings/password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings/personal` | `/settings/personal`; params?: Router.UnknownInputParams; } | { pathname: `/workout/ble`; params?: Router.UnknownInputParams; } | { pathname: `/workout/nfc`; params?: Router.UnknownInputParams; } | { pathname: `/workout/session`; params?: Router.UnknownInputParams; } | { pathname: `/workout/summary`; params?: Router.UnknownInputParams; } | { pathname: `/workout/plan`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings/password` | `/settings/password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings/personal` | `/settings/personal`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/ble`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/nfc`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/session`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/summary`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/plan`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings/password${`?${string}` | `#${string}` | ''}` | `/settings/password${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings/personal${`?${string}` | `#${string}` | ''}` | `/settings/personal${`?${string}` | `#${string}` | ''}` | `/workout/ble${`?${string}` | `#${string}` | ''}` | `/workout/nfc${`?${string}` | `#${string}` | ''}` | `/workout/session${`?${string}` | `#${string}` | ''}` | `/workout/summary${`?${string}` | `#${string}` | ''}` | `/workout/plan${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings/password` | `/settings/password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings/personal` | `/settings/personal`; params?: Router.UnknownInputParams; } | { pathname: `/workout/ble`; params?: Router.UnknownInputParams; } | { pathname: `/workout/nfc`; params?: Router.UnknownInputParams; } | { pathname: `/workout/session`; params?: Router.UnknownInputParams; } | { pathname: `/workout/summary`; params?: Router.UnknownInputParams; } | { pathname: `/workout/plan`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
